version: "3.3"

services:
  currency_web:
    build:
      context: .
      dockerfile: ./docker/Web.Dockerfile
    volumes:
    - ./:/usr/src/app
    ports:
    - 7020:7020
    env_file:
    - .env
    restart: always